<a href="https://colab.research.google.com/github/fboldt/aulasml/blob/master/aula06a_ensembles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_olivetti_faces

X, y = fetch_olivetti_faces(return_X_y=True)
print(X.shape)
print(y.shape)

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data
(400, 4096)
(400,)


In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_hits = knn_pred == y_test
print(knn_hits)
print(knn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.8625


In [6]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)
gnb_hits = gnb_pred == y_test
print(gnb_hits)
print(gnb_hits.mean())

[ True  True  True  True  True  True  True  True  True False  True  True
  True False  True False  True  True  True  True False  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False  True  True  True  True  True False  True  True  True  True  True
  True False  True  True  True False  True  True  True  True  True  True
  True  True  True False  True  True  True False  True False  True  True
  True  True  True  True  True  True False  True]
0.8375


In [7]:
from sklearn.linear_model import Perceptron

ppn = Perceptron(eta0=0.1, random_state=42)
ppn.fit(X_train, y_train)
ppn_pred = ppn.predict(X_test)
ppn_hits = ppn_pred == y_test
print(ppn_hits)
print(ppn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True False  True False  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
  True  True False  True  True  True  True False  True  True  True  True
 False  True  True  True  True  True  True  True]
0.875


In [8]:
import numpy as np

hits = np.stack((knn_hits, gnb_hits, ppn_hits))
print(hits.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]
 [False  True  True]
 [ True  True False]
 [ True  True  True]
 [ True  True False]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True

In [9]:
y_pred = np.stack((knn_pred, gnb_pred, ppn_pred))
print(y_pred.T)

[[20 20 20]
 [28 28 28]
 [ 3  3  3]
 [21 21 21]
 [ 9  9  9]
 [ 8  8  8]
 [32 32 32]
 [ 9  9  9]
 [26 26 26]
 [12 16 12]
 [ 0  0 36]
 [36 36 36]
 [ 5  5  5]
 [ 7 15  7]
 [13 13 13]
 [ 4 34  4]
 [27 27 27]
 [37 37 37]
 [23 23 23]
 [38 38 38]
 [ 7  9  7]
 [ 1  1  1]
 [ 4 39 39]
 [25 27 27]
 [ 0  0  0]
 [ 3 39 39]
 [ 8 11 11]
 [22 22 22]
 [26 26 26]
 [10 15 10]
 [39 39 39]
 [14 19 19]
 [26 26 26]
 [ 5  5  5]
 [23 23 23]
 [11 11 11]
 [12 25 13]
 [20 34 34]
 [15 15 34]
 [14 14 14]
 [38 38 18]
 [ 5  5  5]
 [ 7  9  7]
 [ 2  2  9]
 [ 8  8  8]
 [38 38 38]
 [14 14 14]
 [18 18 18]
 [ 2  2  2]
 [17 39 17]
 [ 4  4 33]
 [32 32 32]
 [33 33 33]
 [ 7  9  7]
 [37 37 37]
 [ 3  3 24]
 [22 22 22]
 [17 17 17]
 [ 3  3  3]
 [ 0 15 15]
 [12 12 12]
 [29 29 29]
 [25 25 32]
 [17  0  7]
 [10 10 10]
 [14  3  3]
 [35 35 35]
 [26 12 27]
 [37 39 39]
 [ 7  9  7]
 [32 32 32]
 [14 14 14]
 [ 0  0 34]
 [ 4  4  4]
 [38 38 38]
 [24 24 24]
 [22 22 22]
 [36 36 36]
 [17  9 17]
 [28 28 28]]


In [10]:
from scipy.stats import mode

y_pred_mode, _ = mode(y_pred, axis=0)
vote_hits = y_pred_mode == y_test
print(vote_hits)
print(vote_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [13]:
from sklearn.base import BaseEstimator, ClassifierMixin

class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers):
        self.classifiers = classifiers

    def fit(self, X, y):
        for _, clf in self.classifiers:
            clf.fit(X, y)
        return self

    def predict(self, X):
        y_pred = np.stack([clf.predict(X) for _, clf in self.classifiers])
        y_pred_mode, _ = mode(y_pred, axis=0)
        return y_pred_mode

base_estimators = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron(eta0=0.1, random_state=42))
]
mv_clf = MajorityVoteClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = mv_clf_pred == y_test
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [15]:
from sklearn.ensemble import VotingClassifier

base_estimators = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron(eta0=0.1, random_state=42))
]
voting_clf = VotingClassifier(base_estimators, voting='hard')
voting_clf.fit(X_train, y_train)
voting_clf_pred = voting_clf.predict(X_test)
voting_clf_hits = voting_clf_pred == y_test
print(voting_clf_hits)
print(voting_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [24]:
ks = [1, 3, 5]
base_estimators = [(f"KNN({k})", KNeighborsClassifier(k)) for k in ks]
voting_clf = VotingClassifier(base_estimators, voting='hard')
voting_clf.fit(X_train, y_train)
voting_clf_pred = voting_clf.predict(X_test)
voting_clf_hits = voting_clf_pred == y_test
print(voting_clf_hits)
print(voting_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True False  True  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.9


In [29]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)
dtc_hits = dtc_pred == y_test
print(dtc_hits)
print(dtc_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False  True  True  True  True  True  True False  True
  True  True False False False False False  True False False  True False
 False False False  True False False False False  True False  True  True
  True False False  True  True False  True False False False False  True
 False  True False False False  True  True  True False False  True  True
 False False  True  True  True False  True  True]
0.5


In [26]:
base_estimators = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('dtc', DecisionTreeClassifier()),
    ('ppn', Perceptron(eta0=0.1, random_state=42))
]
voting_clf = VotingClassifier(base_estimators, voting='hard')
voting_clf.fit(X_train, y_train)
voting_clf_pred = voting_clf.predict(X_test)
voting_clf_hits = voting_clf_pred == y_test
print(voting_clf_hits)
print(voting_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True False  True  True  True  True  True  True  True  True  True
 False False False  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False  True  True  True
  True  True  True  True  True  True  True  True]
0.9


In [30]:
base_estimators = [(f"dtc({i})", DecisionTreeClassifier()) for i in range(10)]

voting_clf = VotingClassifier(base_estimators, voting='hard')
voting_clf.fit(X_train, y_train)
voting_clf_pred = voting_clf.predict(X_test)
voting_clf_hits = voting_clf_pred == y_test
print(voting_clf_hits)
print(voting_clf_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False False  True  True  True  True  True False False
  True  True False False False False False  True  True False False False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False False  True  True  True False False  True False
 False  True  True  True  True False  True  True]
0.5


In [45]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(splitter='random')
dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)
dtc_hits = dtc_pred == y_test
print(dtc_hits)
print(dtc_hits.mean())

[ True  True  True  True False False  True  True  True False  True  True
  True False  True  True False  True False False False  True  True False
  True False  True  True  True False  True  True False  True  True  True
 False False False  True False  True False  True  True False  True  True
  True  True False  True  True  True  True  True False  True  True  True
 False  True False False False False  True False False False  True  True
  True  True False  True  True False  True False]
0.6125


In [48]:
base_estimators = [(f"dtc({i})", DecisionTreeClassifier(splitter="random")) for i in range(10)]

voting_clf = VotingClassifier(base_estimators, voting='hard')
voting_clf.fit(X_train, y_train)
voting_clf_pred = voting_clf.predict(X_test)
voting_clf_hits = voting_clf_pred == y_test
print(voting_clf_hits)
print(voting_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True False False
  True  True  True  True  True  True False  True  True  True  True  True
 False False False  True False  True False False  True  True  True  True
  True  True False  True  True  True  True  True False  True  True  True
  True  True False False  True False  True  True False False  True  True
  True  True  True  True  True  True  True  True]
0.7875


In [57]:
from sklearn.ensemble import BaggingClassifier

base_estimator = DecisionTreeClassifier()
bagging_clf = BaggingClassifier(base_estimator,
                                n_estimators=10)
bagging_clf.fit(X_train, y_train)
bagging_clf_pred = bagging_clf.predict(X_test)
bagging_clf_hits = bagging_clf_pred == y_test
print(bagging_clf_hits)
print(bagging_clf_hits.mean())

[ True  True  True  True  True False  True  True  True False  True  True
  True False  True  True False  True  True  True  True  True False  True
  True  True  True  True  True  True False  True  True  True  True  True
 False False False  True False  True False  True False False  True  True
  True  True False  True  True False  True  True False  True False  True
  True  True False False  True  True  True  True False False  True  True
  True  True  True  True  True  True False  True]
0.725


In [59]:
base_estimator = DecisionTreeClassifier(splitter='random')
bagging_clf = BaggingClassifier(base_estimator,
                                n_estimators=100)
bagging_clf.fit(X_train, y_train)
bagging_clf_pred = bagging_clf.predict(X_test)
bagging_clf_hits = bagging_clf_pred == y_test
print(bagging_clf_hits)
print(bagging_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True False  True  True  True
  True  True False False  True  True  True  True False False  True  True
  True  True  True  True  True  True  True  True]
0.9125


In [60]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train, y_train)
rf_clf_pred = rf_clf.predict(X_test)
rf_clf_hits = rf_clf_pred == y_test
print(rf_clf_hits)
print(rf_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True False  True  True  True
  True  True False False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.9125


In [64]:
from sklearn.ensemble import ExtraTreesClassifier

et_clf = ExtraTreesClassifier(n_estimators=100)
et_clf.fit(X_train, y_train)
et_clf_pred = et_clf.predict(X_test)
et_clf_hits = et_clf_pred == y_test
print(et_clf_hits)
print(et_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [79]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

base_estimator = DecisionTreeClassifier(max_depth=20, splitter='random')
ada_clf = AdaBoostClassifier(base_estimator)
ada_clf.fit(X_train, y_train)
y_pred = ada_clf.predict(X_test)
accuracy_score(y_test, y_pred), accuracy_score(y_train, ada_clf.predict(X_train))

(0.925, 1.0)

In [84]:
from sklearn.ensemble import StackingClassifier

base_estimators = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron(eta0=0.1, random_state=42))
]
stacking_clf = StackingClassifier(base_estimators, cv=3)
stacking_clf.fit(X_train, y_train)
stacking_clf_pred = stacking_clf.predict(X_test)
stacking_clf_hits = stacking_clf_pred == y_test
print(stacking_clf_hits)
print(stacking_clf_hits.mean())


[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True False  True  True  True  True
  True False  True False  True  True  True  True  True  True  True  True
 False  True False  True False  True  True  True  True False  True  True
  True  True  True  True  True False  True  True False  True  True  True
  True  True  True False  True False  True False  True False  True  True
 False  True  True  True False  True  True  True]
0.8


In [93]:
voting_clf = VotingClassifier([
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron(eta0=0.1, random_state=42))
])
base_estimators = [
    ('voting', voting_clf),
    ('random_forest', RandomForestClassifier(n_estimators=100)),
    ('extra_trees', ExtraTreesClassifier(n_estimators=100))
]

stacking_clf = StackingClassifier(base_estimators, cv=3)
stacking_clf.fit(X_train, y_train)
stacking_clf_pred = stacking_clf.predict(X_test)
stacking_clf_hits = stacking_clf_pred == y_test
print(stacking_clf_hits)
print(stacking_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True False  True
  True False  True  True  True  True  True  True False  True False  True
 False False  True False  True  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True False  True False False  True  True  True
  True  True  True False  True False  True False False False  True  True
 False  True  True  True False  True  True  True]
0.7625


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [92]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
lr_clf_pred = lr_clf.predict(X_test)
lr_clf_hits = lr_clf_pred == y_test
print(lr_clf_hits)
print(lr_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.975


In [102]:
from sklearn.model_selection import cross_val_score, StratifiedKFold

lr_clf = LogisticRegression(tol=0.001)
scores = cross_val_score(lr_clf, X, y, cv=StratifiedKFold(n_splits=5), verbose=3)
print(scores)
print(scores.mean())

[CV] END ................................ score: (test=1.000) total time=   6.2s
[CV] END ................................ score: (test=0.950) total time=  10.5s
[CV] END ................................ score: (test=0.950) total time=   8.7s
[CV] END ................................ score: (test=0.975) total time=   5.6s
[CV] END ................................ score: (test=0.950) total time=   5.6s
[1.    0.95  0.95  0.975 0.95 ]
0.9650000000000001


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   36.6s finished


In [103]:
!pip install optuna -qq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 7.7 MB/s eta 0:00:00


In [105]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
import optuna

def objective(trial):
    # AdaBoostClassifier hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 1.0, log=True)

    # DecisionTreeClassifier hyperparameters for the base estimator
    max_depth = trial.suggest_int('max_depth', 1, 30)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 20)

    base_estimator = DecisionTreeClassifier(
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        splitter='random'
    )

    ada_clf = AdaBoostClassifier(
        estimator=base_estimator,
        n_estimators=n_estimators,
        learning_rate=learning_rate
    )

    # Evaluate the model using cross-validation
    kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = cross_val_score(ada_clf, X_train, y_train, cv=kf, scoring='accuracy')

    return scores.mean()

# Create an Optuna study and optimize
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50) # You can adjust n_trials for more extensive search

print(f"Number of finished trials: {len(study.trials)}")
print(f"Best trial:")
print(f"  Value: {study.best_value}")
print(f"  Params:")
for key, value in study.best_params.items():
    print(f"    {key}: {value}")


[I 2026-04-29 00:18:00,922] A new study created in memory with name: no-name-0be1153b-e4a6-4060-ac8a-06bf94885534
[I 2026-04-29 00:18:14,296] Trial 0 finished with value: 0.1405689766649033 and parameters: {'n_estimators': 127, 'learning_rate': 0.13214544826907396, 'max_depth': 1, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.1405689766649033.
[I 2026-04-29 00:19:18,438] Trial 1 finished with value: 0.9093634279668489 and parameters: {'n_estimators': 197, 'learning_rate': 0.49065886536187375, 'max_depth': 17, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.9093634279668489.
[I 2026-04-29 00:19:32,027] Trial 2 finished with value: 0.8155822018456474 and parameters: {'n_estimators': 57, 'learning_rate': 0.061818323878445665, 'max_depth': 11, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.9093634279668489.
[I 2026-04-29 00:19:51,108] Trial 3 finished with value: 0.7814318462352318 and parameters: {'n_estimators': 118, 'learning_rate': 0.03940040458753066, 'max_depth':

Number of finished trials: 50
Best trial:
  Value: 0.9093634279668489
  Params:
    n_estimators: 197
    learning_rate: 0.49065886536187375
    max_depth: 17
    min_samples_leaf: 8


In [106]:
best_params = study.best_params

best_base_estimator = DecisionTreeClassifier(
    max_depth=best_params['max_depth'],
    min_samples_leaf=best_params['min_samples_leaf'],
    splitter='random',
    random_state=42
)

best_ada_clf = AdaBoostClassifier(
    estimator=best_base_estimator,
    n_estimators=best_params['n_estimators'],
    learning_rate=best_params['learning_rate'],
    random_state=42
)

best_ada_clf.fit(X_train, y_train)

y_pred_best = best_ada_clf.predict(X_test)
accuracy_best = accuracy_score(y_test, y_pred_best)

print(f"Accuracy on test set with best hyperparameters: {accuracy_best}")

Accuracy on test set with best hyperparameters: 0.9125
