<a href="https://colab.research.google.com/github/fboldt/aulasml/blob/master/aula07a_ensembles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
print(X.shape)
print(y.shape)

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data
(400, 4096)
(400,)


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_hits = (knn_pred == y_test)
print(knn_hits)
print(knn_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.8625


In [12]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)
gnb_hits = (gnb_pred == y_test)
print(gnb_hits)
print(gnb_hits.mean())

[ True  True  True  True  True  True  True  True  True False  True  True
  True False  True False  True  True  True  True False  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
 False  True  True  True  True  True False  True  True  True  True  True
  True False  True  True  True False  True  True  True  True  True  True
  True  True  True False  True  True  True False  True False  True  True
  True  True  True  True  True  True False  True]
0.8375


In [14]:
from sklearn.linear_model import Perceptron
ppn = Perceptron()
ppn.fit(X_train, y_train)
ppn_pred = ppn.predict(X_test)
ppn_hits = (ppn_pred == y_test)
print(ppn_hits)
print(ppn_hits.mean())

[ True  True  True  True  True  True  True  True  True False False  True
  True False  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True False  True  True False False  True
  True  True  True  True False  True False False  True  True  True  True
  True  True  True  True  True  True  True False  True  True  True  True
  True  True  True False  True False  True False False  True  True  True
 False  True  True  True  True  True  True  True]
0.8


In [15]:
import numpy as np
hits = np.stack((knn_hits, gnb_hits, ppn_hits))
print(hits.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True False False]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [False  True False]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True False]
 [False  True  True]
 [ True  True  True]
 [ True  True False]
 [ True  True False]
 [ True  True  True]
 [False False  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True False]
 [ True  True  True]
 [ True False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True

In [16]:
y_pred = np.stack((knn_pred, gnb_pred, ppn_pred))
print(y_pred.T)

[[20 20 20]
 [28 28 28]
 [ 3  3  3]
 [21 21 21]
 [ 9  9  9]
 [ 8  8  8]
 [32 32 32]
 [ 9  9  9]
 [26 26 26]
 [12 16 28]
 [ 0  0 32]
 [36 36 36]
 [ 5  5  5]
 [ 7 15 34]
 [13 13 13]
 [ 4 34  4]
 [27 27 27]
 [37 37 37]
 [23 23 23]
 [38 38 38]
 [ 7  9  7]
 [ 1  1  1]
 [ 4 39  2]
 [25 27 27]
 [ 0  0  0]
 [ 3 39 39]
 [ 8 11 11]
 [22 22 22]
 [26 26 26]
 [10 15 10]
 [39 39  2]
 [14 19 19]
 [26 26 26]
 [ 5  5  8]
 [23 23 28]
 [11 11 11]
 [12 25 11]
 [20 34 34]
 [15 15 15]
 [14 14 14]
 [38 38 36]
 [ 5  5  5]
 [ 7  9 32]
 [ 2  2 36]
 [ 8  8  8]
 [38 38 38]
 [14 14 14]
 [18 18 18]
 [ 2  2  2]
 [17 39 17]
 [ 4  4  4]
 [32 32 32]
 [33 33 33]
 [ 7  9  7]
 [37 37 37]
 [ 3  3  8]
 [22 22 22]
 [17 17 17]
 [ 3  3  3]
 [ 0 15 15]
 [12 12 12]
 [29 29 29]
 [25 25 25]
 [17  0 28]
 [10 10 10]
 [14  3 19]
 [35 35 35]
 [26 12 36]
 [37 39 30]
 [ 7  9  7]
 [32 32 32]
 [14 14 14]
 [ 0  0 31]
 [ 4  4  4]
 [38 38 38]
 [24 24 24]
 [22 22 22]
 [36 36 36]
 [17  9 17]
 [28 28 28]]


In [17]:
from scipy.stats import mode
y_pred_mode, _ = mode(y_pred, axis=0)
vote_hits = (y_pred_mode == y_test)
print(vote_hits)
print(vote_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False False  True  True  True
  True  True  True  True  True  True  True  True]
0.95


In [20]:
from sklearn.base import BaseEstimator, ClassifierMixin

class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers):
        self.classifiers = classifiers

    def fit(self, X, y):
        for _, clf in self.classifiers:
            clf.fit(X, y)

    def predict(self, X):
        y_preds = []
        for _, clf in self.classifiers:
            y_preds.append(clf.predict(X))
        y_preds = np.stack(y_preds)
        y_pred_mode, _ = mode(y_preds, axis=0)
        return y_pred_mode

base_estimators = [
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron())
]

mv_clf = MajorityVoteClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = (mv_clf_pred == y_test)
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False False  True  True  True
  True  True  True  True  True  True  True  True]
0.95


In [21]:
from sklearn.ensemble import VotingClassifier

mv_clf = VotingClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = (mv_clf_pred == y_test)
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True False False  True  True  True
  True  True  True  True  True  True  True  True]
0.95


In [25]:
ks = [1, 5 ,9]
base_estimators = [(f"KNN({k})", KNeighborsClassifier(k)) for k in ks]
mv_clf = MajorityVoteClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = (mv_clf_pred == y_test)
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
  True False False  True  True  True  True False  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True False  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.875


In [30]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
dt_hits = (dt_pred == y_test)
print(dt_hits)
print(dt_hits.mean())

[ True False  True  True  True False  True False False False False  True
  True False False  True False  True  True  True  True  True False  True
  True False False False False  True False  True False False False False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False False  True  True  True False False  True False
 False  True  True  True  True False  True False]
0.475


In [35]:
base_estimators = [
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('dt', DecisionTreeClassifier())
]

mv_clf = VotingClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = (mv_clf_pred == y_test)
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True  True  True  True  True False  True  True
  True False  True False  True  True  True  True  True  True False False
  True  True False  True  True  True  True  True  True  True  True  True
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True False False  True  True
  True  True  True  True  True  True False  True]
0.85


In [88]:
base_estimators = [(f"dt({i})", DecisionTreeClassifier()) for i in range(10)]

mv_clf = VotingClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = (mv_clf_pred == y_test)
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True False  True  True False False False  True
  True False False False False  True  True  True  True  True False  True
  True  True False False False  True False  True  True False False False
 False False False  True False  True False False  True False  True  True
  True  True False  True  True False  True False False False False  True
 False  True False False  True  True  True  True False False  True  True
 False  True  True  True  True False  True  True]
0.55


In [89]:
base_estimators = [(f"dt({i})", DecisionTreeClassifier(splitter='random')) for i in range(10)]

mv_clf = VotingClassifier(base_estimators)
mv_clf.fit(X_train, y_train)
mv_clf_pred = mv_clf.predict(X_test)
mv_clf_hits = (mv_clf_pred == y_test)
print(mv_clf_hits)
print(mv_clf_hits.mean())

[ True  True  True  True  True False  True  True  True False  True  True
  True  True  True  True False  True  True  True  True  True  True False
  True  True  True  True  True False  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True False  True  True False  True  True False  True  True  True
  True  True False False  True False  True  True False False  True  True
  True  True  True  True  True False  True  True]
0.8125


In [90]:
from sklearn.ensemble import BaggingClassifier

base_estimator = DecisionTreeClassifier()
bagging = BaggingClassifier(base_estimator,
                            n_estimators=10,
                            random_state=42)
bagging.fit(X_train, y_train)
bagging_pred = bagging.predict(X_test)
bagging_hits = (bagging_pred == y_test)
print(bagging_hits)
print(bagging_hits.mean())

[ True  True  True  True  True  True  True  True  True False  True  True
  True  True  True  True False False  True  True  True  True False False
  True False  True  True  True False  True  True  True  True  True False
 False  True  True  True False  True  True False False False  True  True
  True False False  True  True False  True  True False  True  True  True
  True  True False False  True False  True False False False False  True
  True  True  True  True  True False False  True]
0.675


In [91]:
from sklearn.ensemble import BaggingClassifier

base_estimator = DecisionTreeClassifier(splitter='random')
bagging = BaggingClassifier(base_estimator,
                            n_estimators=10,
                            random_state=42)
bagging.fit(X_train, y_train)
bagging_pred = bagging.predict(X_test)
bagging_hits = (bagging_pred == y_test)
print(bagging_hits)
print(bagging_hits.mean())

[ True  True  True  True  True  True  True False  True False  True  True
  True False  True  True False  True  True  True  True  True False False
  True False False  True  True  True False  True  True  True  True False
 False False  True  True False  True False  True  True False  True  True
  True  True  True  True  True  True  True False  True False  True  True
  True  True False False  True False  True False False False  True  True
  True  True  True  True  True False False  True]
0.6875


In [98]:
from sklearn.ensemble import BaggingClassifier

base_estimator = DecisionTreeClassifier(splitter='random')
bagging = BaggingClassifier(base_estimator,
                            n_estimators=100,
                            random_state=42)
bagging.fit(X_train, y_train)
bagging_pred = bagging.predict(X_test)
bagging_hits = (bagging_pred == y_test)
print(bagging_hits)
print(bagging_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True False  True  True False False  True  True
  True  True  True  True  True  True  True  True]
0.9125


In [99]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100,
                            random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_hits = (rf_pred == y_test)
print(rf_hits)
print(rf_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
  True  True False False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.925


In [100]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_estimators=100,
                            random_state=42)
et.fit(X_train, y_train)
et_pred = et.predict(X_test)
et_hits = (et_pred == y_test)
print(et_hits)
print(et_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
0.9625


In [110]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(DecisionTreeClassifier(max_depth=20, splitter='random'),
                         learning_rate=0.15, random_state=42)
ada.fit(X_train, y_train)
ada_pred = ada.predict(X_test)
ada_hits = (ada_pred == y_test)
print(ada_hits)
print(ada_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True False  True  True  True  True  True False  True  True  True
  True  True False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
0.925


In [118]:
from sklearn.ensemble import StackingClassifier
import warnings
warnings.filterwarnings('ignore')

voting = VotingClassifier([
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('ppn', Perceptron())
])

base_estimators = [
    ('voting', voting),
    ('rf', RandomForestClassifier()),
    ('et', ExtraTreesClassifier())
]

stacking = StackingClassifier(base_estimators,
                              cv=3, passthrough=True)
stacking.fit(X_train, y_train)
stacking_pred = stacking.predict(X_test)
stacking_hits = (stacking_pred == y_test)
print(stacking_hits)
print(stacking_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.975


In [119]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_hits = (lr_pred == y_test)
print(lr_hits)
print(lr_hits.mean())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True]
0.975


In [130]:
from sklearn.model_selection import cross_validate, StratifiedKFold
from pprint import pprint
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
scores = cross_validate(lr, X, y, cv=StratifiedKFold(), return_train_score=True)
pprint(scores)
print(scores['test_score'].mean())

{'fit_time': array([11.33430243, 11.98795342, 11.24827361, 11.28192091, 10.66648602]),
 'score_time': array([0.00576997, 0.02064586, 0.00738096, 0.10807204, 0.00335217]),
 'test_score': array([1.   , 0.95 , 0.95 , 0.975, 0.95 ]),
 'train_score': array([1., 1., 1., 1., 1.])}
0.9650000000000001


In [124]:
!pip install optuna -qq

In [ ]:
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn.ensemble import VotingClassifier, RandomForestClassifier, ExtraTreesClassifier, StackingClassifier
from sklearn.tree import DecisionTreeClassifier
import warnings
import numpy as np

warnings.filterwarnings('ignore')

def objective(trial):
    # Define hyperparameters for base estimators
    knn_n_neighbors = trial.suggest_int('knn_n_neighbors', 1, 20)
    gnb_var_smoothing = trial.suggest_float('gnb_var_smoothing', 1e-10, 1e-8, log=True)
    ppn_eta0 = trial.suggest_float('ppn_eta0', 0.0001, 1.0, log=True)

    # Define hyperparameters for the meta-classifier (Logistic Regression)
    lr_C = trial.suggest_float('lr_C', 0.01, 10.0, log=True)
    lr_solver = trial.suggest_categorical('lr_solver', ['liblinear', 'lbfgs', 'newton-cg', 'sag', 'saga'])

    # Define hyperparameters for the ensemble methods within the stacking
    rf_n_estimators = trial.suggest_int('rf_n_estimators', 50, 300)
    et_n_estimators = trial.suggest_int('et_n_estimators', 50, 300)

    stacking_passthrough = trial.suggest_categorical('stacking_passthrough', [True, False])

    # Create base estimators with suggested hyperparameters
    knn = KNeighborsClassifier(n_neighbors=knn_n_neighbors)
    gnb = GaussianNB(var_smoothing=gnb_var_smoothing)
    ppn = Perceptron(eta0=ppn_eta0)
    lr = LogisticRegression(C=lr_C, solver=lr_solver)
    rf = RandomForestClassifier(n_estimators=rf_n_estimators, random_state=42)
    et = ExtraTreesClassifier(n_estimators=et_n_estimators, random_state=42)

    # Create the VotingClassifier
    voting = VotingClassifier([
        ('knn', knn),
        ('gnb', gnb),
        ('ppn', ppn)
    ])

    # Create the StackingClassifier
    base_estimators = [
        ('voting', voting),
        ('rf', rf),
        ('et', et)
    ]

    stacking = StackingClassifier(base_estimators,
                                  final_estimator=lr,
                                  cv=3,
                                  passthrough=stacking_passthrough)

    # Evaluate the StackingClassifier using cross-validation
    score = cross_val_score(stacking, X_train, y_train, n_jobs=-1, cv=3).mean()
    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

print("Best parameters found by Optuna:")
print(study.best_params)
print("Best cross-validation score (negative MSE):")
print(study.best_value)

[I 2025-09-25 00:25:22,249] A new study created in memory with name: no-name-2ab73e3d-1e1c-4300-a70a-68c8f509f31e
[I 2025-09-25 00:26:18,732] Trial 0 finished with value: 0.3126432727913948 and parameters: {'knn_n_neighbors': 18, 'gnb_var_smoothing': 4.671470755945215e-10, 'ppn_eta0': 0.005886995306825281, 'lr_C': 1.7594711581067959, 'lr_solver': 'saga', 'rf_n_estimators': 124, 'et_n_estimators': 293, 'stacking_passthrough': False}. Best is trial 0 with value: 0.3126432727913948.
[I 2025-09-25 00:28:07,656] Trial 1 finished with value: 0.9155939575618645 and parameters: {'knn_n_neighbors': 15, 'gnb_var_smoothing': 1.1377214860904804e-10, 'ppn_eta0': 0.14954309829262577, 'lr_C': 1.0096816957968953, 'lr_solver': 'sag', 'rf_n_estimators': 242, 'et_n_estimators': 212, 'stacking_passthrough': True}. Best is trial 1 with value: 0.9155939575618645.
[I 2025-09-25 00:28:49,859] Trial 2 finished with value: 0.37800505495797326 and parameters: {'knn_n_neighbors': 5, 'gnb_var_smoothing': 4.2961085