<a href="https://colab.research.google.com/github/fboldt/aulasml/blob/master/aula10c_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_covtype
X, y = fetch_covtype(return_X_y=True)
print(X.shape)
print(y.shape)

(581012, 54)
(581012,)


In [2]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import RidgeClassifier
import numpy as np

modelo = RidgeClassifier()
scores = cross_validate(modelo, X, y)
print(scores['test_score'])
print(np.mean(scores['test_score']))

[0.58947704 0.76359474 0.62652106 0.67569405 0.54031772]
0.639120922063683


In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import PCA

modelo = make_pipeline(PCA(n_components=0.99), RidgeClassifier())
scores = cross_validate(modelo, X, y)
print(scores['test_score'])
print(np.mean(scores['test_score']))

[0.51089042 0.71047219 0.60088467 0.64610764 0.48564569]
0.5908001215768827


In [8]:
modelo.fit(X, y)

Pipeline(steps=[('pca', PCA(n_components=0.99)),
                ('ridgeclassifier', RidgeClassifier())])

In [12]:
modelo.named_steps['pca'].singular_values_

array([1290498.80392529,  878997.25026923,  211037.15698798,
        146986.30620276])

In [13]:
from sklearn.preprocessing import StandardScaler

modelo = make_pipeline(StandardScaler(), PCA(n_components=0.99), RidgeClassifier())
scores = cross_validate(modelo, X, y)
print(scores['test_score'])
print(np.mean(scores['test_score']))

[0.59180056 0.66395876 0.58561815 0.66244987 0.57718456]
0.6162023790307951


In [15]:
modelo.fit(X, y)
tmp = modelo.named_steps['pca'].singular_values_
tmp, len(tmp)

(array([1466.15987578, 1302.65336693, 1180.39733969, 1078.77518739,
         940.08907934,  921.92882477,  844.85268368,  823.01510238,
         800.58747491,  793.70233939,  789.97310264,  787.51866665,
         782.83262938,  776.73475776,  775.97013781,  774.46966877,
         772.27916527,  771.55406898,  770.46157501,  768.48723166,
         767.67524538,  767.36255575,  766.14469266,  765.72424555,
         765.21262046,  764.73855573,  764.64363755,  763.90865971,
         763.81401376,  763.77454487,  763.67553115,  763.39683732,
         763.11939371,  762.71325413,  762.6209443 ,  762.5236505 ,
         762.41770461,  762.32796814,  762.24574228,  754.46196157,
         692.49433252,  684.26926167,  611.65837198,  606.86000755,
         517.15649314,  491.46619213,  435.8028929 ,  409.72905139,
         382.1401579 ]),
 49)