<a href="https://colab.research.google.com/github/fboldt/aulasml/blob/master/aula8c_ensembles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
Xtr, Xte, ytr, yte = train_test_split(X, y, random_state=42)
Xtr.shape, Xte.shape

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data


((300, 4096), (100, 4096))

In [80]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(Xtr, ytr)
knn_pr = knn.predict(Xte)
knn_hits = (knn_pr == yte)
print(knn_hits.sum() / len(knn_hits))
knn_hits

0.83


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True,  True, False, False,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [81]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(Xtr, ytr)
gnb_pr = gnb.predict(Xte)
gnb_hits = (gnb_pr == yte)
print(gnb_hits.sum() / len(gnb_hits))
gnb_hits

0.81


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False])

In [82]:
from sklearn.linear_model import Perceptron
per = Perceptron()
per.fit(Xtr, ytr)
per_pr = per.predict(Xte)
per_hits = (per_pr == yte)
print(per_hits.sum() / len(per_hits))
per_hits

0.78


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False])

In [83]:
import numpy as np
hits = np.array([knn_hits, gnb_hits, per_hits])
hits.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ T

In [84]:
ypr = np.array([knn_pr, gnb_pr, per_pr])
ypr.T

array([[20, 20, 20],
       [28, 28, 28],
       [ 3,  3,  3],
       [21, 21, 21],
       [ 9,  9,  9],
       [ 8,  8,  8],
       [32, 32, 32],
       [ 9,  9,  9],
       [26, 26, 26],
       [12, 16, 28],
       [ 0,  0,  0],
       [36, 36, 36],
       [ 5,  5,  8],
       [ 7, 15,  7],
       [13, 13, 13],
       [ 4, 34, 29],
       [25, 27, 25],
       [37, 37, 37],
       [23, 23, 23],
       [38, 38, 38],
       [ 7, 15,  7],
       [ 1,  1,  1],
       [ 4, 39, 39],
       [25, 27, 25],
       [ 0,  0,  0],
       [ 3, 39, 39],
       [11, 11, 11],
       [22, 22, 22],
       [26, 26, 26],
       [10, 15, 10],
       [29, 39, 39],
       [29, 19, 19],
       [26, 26, 26],
       [ 5,  5, 29],
       [20, 23, 23],
       [11, 11, 11],
       [12, 39, 11],
       [20, 34, 34],
       [15, 15, 15],
       [14, 14, 14],
       [38, 38, 38],
       [ 5,  5, 29],
       [ 7,  9,  7],
       [ 2,  2, 36],
       [ 8,  8,  8],
       [28, 38, 28],
       [14, 14, 14],
       [18, 1

In [85]:
from scipy import stats
ypr = stats.mode(ypr)[0].reshape(-1)
vot_hits = (ypr == yte)
print(vot_hits.sum() / len(vot_hits))
vot_hits

0.91


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

##  Combinação de Classificadores

In [86]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([('knn', knn), ('gnb', gnb), ('per', per)])
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.91


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [87]:
modelo = VotingClassifier([
    ('knn1', KNeighborsClassifier(1)),
    ('knn5', KNeighborsClassifier(5)),
    ('knn9', KNeighborsClassifier(9))])
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.84


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False])

In [90]:
from sklearn.tree import DecisionTreeClassifier
modelo = VotingClassifier([
    ('knn', knn),
    ('gnb', gnb),
    ('dtc', DecisionTreeClassifier(random_state=42))])
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.8


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [91]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.4


array([False,  True, False,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False,  True, False,  True,  True, False,
        True, False, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False, False,  True, False,
       False])

## Diversificação por reamostragem

In [92]:
modelo = DecisionTreeClassifier()
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.48


array([False, False, False,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False, False,  True, False, False,  True, False,  True,  True,
       False, False,  True,  True,  True, False,  True,  True, False,
        True, False, False, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False, False,  True, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [93]:
from sklearn.ensemble import BaggingClassifier
modelo = BaggingClassifier(DecisionTreeClassifier(), n_estimators=10)
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.61


array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True, False, False,  True,
        True,  True, False,  True, False, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True, False, False,  True, False,  True, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True, False, False, False,  True,  True,  True,  True, False,
       False,  True, False,  True, False, False, False,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False])

In [96]:
modelo = BaggingClassifier()
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.65


array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True, False, False,  True, False,  True,
        True, False, False,  True,  True, False,  True, False, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False,  True, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False])

## Aumentando a aleatoriedade para aumentar a diversidade

In [102]:
modelo = BaggingClassifier(estimator=DecisionTreeClassifier(splitter='random'))
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.75


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False])

In [104]:
modelo = BaggingClassifier(estimator=DecisionTreeClassifier(splitter='random'),
                           n_estimators=100)
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.86


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

## Random Forest é um Bagging de Árvores de Decisão

In [105]:
from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier()
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.92


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Regularização do Bagging

In [106]:
modelo = BaggingClassifier(estimator=DecisionTreeClassifier(splitter='random'),
                           n_estimators=100, max_features=0.15)
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.91


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

## Florestas extremamente aleatórias

In [107]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.93


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Boosting

In [108]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier()
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


0.07


array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [109]:
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(DecisionTreeClassifier(splitter='random', max_depth=25),
                            learning_rate=0.15)
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


0.73


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False, False, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False])

In [111]:
from xgboost import XGBClassifier
modelo = XGBClassifier()
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.71


array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False, False,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [112]:
modelo = XGBClassifier(colsample_bynode=0.01, learning_rate=0.15)
modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.87


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [113]:
import warnings
warnings.filterwarnings('ignore')

In [117]:
from sklearn.ensemble import StackingClassifier

voting = VotingClassifier([
    ('knn', knn),
    ('gnb', gnb),
    ('per', per)])

modelo = StackingClassifier([
    ('voting', voting),
    ('extrees', ExtraTreesClassifier()),
    ('randfor', RandomForestClassifier())], passthrough=True)

modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.94


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [118]:
modelo = StackingClassifier([
    ('randfor42', RandomForestClassifier(random_state=42)),
    ('randfor43', RandomForestClassifier(random_state=43)),
    ('randfor44', RandomForestClassifier(random_state=44))], passthrough=True)

modelo.fit(Xtr, ytr)
modelo_pr = modelo.predict(Xte)
modelo_hits = (modelo_pr == yte)
print(modelo_hits.sum() / len(modelo_hits))
modelo_hits

0.95


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])